#DataSource 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PetProject
    password: pet
  thymeleaf : 
    cache : false
    prefix : classpath:/templates/
    suffix : .html

#image, css, js
#  mvc:
##    static-path-pattern: /resources/**
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
      


#myBatis 설정 : *로 설정하면 해당 위치에 있는 모든 mapper 등록
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.dto
  

#server 설정
server:
  port: 8096
  servlet:
    context-path: /
    
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
  - /**

logging:
  config: classpath:log4j/log4j2.xml


#타임리프
#prefix: /templates/
#suffix: .html