#DataSource 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PetProject
    password: pet

#image, css, js
  mvc:
    static-path-pattern: /resources/**
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER   
  thymeleaf :
    prefix : /templates/
    suffix : .html


#myBatis 설정 : *로 설정하면 해당 위치에 있는 모든 mapper 등록
mybatis:
  mapper-locations: com/example/mapper/*.xml
  type-aliases-package: com.example.dto
  

#server 설정
server:
  port: 8090
  servlet:
    context-path: /app


logging:
  config: classpath:log4j/log4j2.xml



